name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ vars.DH_HOST }}
          username: ${{ vars.DH_USER }}
          ssh_private_key: ${{ secrets.DH_KEY }}
          local_path: "./"          # everything in repo
          remote_path: "/home/${{ vars.DH_USER }}/jmh2025.xyz"
          args: "-o StrictHostKeyChecking=no"
