name: Deploy Root Site to DreamHost

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.9'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build site
        run: |
          npm run build

      - name: Deploy via rsync over SSH
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./build/
          remote_path: /home/${{ secrets.DREAMHOST_USER }}/jmh2025.xyz/
          remote_host: ${{ secrets.DREAMHOST_HOST }}
          remote_user: ${{ secrets.DREAMHOST_USER }}
          remote_key: ${{ secrets.DREAMHOST_SSH_KEY }}
